<?php

/*
|--------------------------------------------------------------------------
| Blog
|--------------------------------------------------------------------------
|
| These settings are used to properly generate your  blog  using Sereno.
| If _blog directory is present in the `content` directory, then the
| blog is generated automatically.
|
*/
return [
    /*
    |--------------------------------------------------------------------------
    | Directory
    |--------------------------------------------------------------------------
    |
    | Here you may specify which directory (relative to content) to use
    | for generating your blog.
    |
    */
    'directory' => 'blog',

    /*
    |--------------------------------------------------------------------------
    | URL prefix
    |--------------------------------------------------------------------------
    |
    | Pages generated by Blog builder are prefixed with this value.
    |
    */
    'url_prefix' => 'blog',
    /*
    |--------------------------------------------------------------------------
    | Articles Per Page
    |--------------------------------------------------------------------------
    |
    | Blog builder creates an index of your articles, listed on the landing
    | page of your blog. This value controls number of articles listed
    | per page of the index.
    |
    */
    'postsPerPage' => 15,

    /*
    |--------------------------------------------------------------------------
    | Markdown Configuration for Articles
    |--------------------------------------------------------------------------
    |
    | Use these configurations for markdown pages in blog.
    |
    */
    'post' => [
        'extends' => 'blog.post',
        'yields'  => 'post-content',
    ],

    /*
    |--------------------------------------------------------------------------
    | Disqus Comments
    |--------------------------------------------------------------------------
    |
    | You can add comments to your blog articles. Set `enable_comments` to
    | true and put your Disqus site ID in `disqus_id`.
    |
    */
    'enable_comments' => true,
    'disqus_id'       => '',
];
